apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
    replicas: 2
    selector:
      matchLabels:
        app: monitoring-pod
    template:
      metadata:
        labels:
          app: monitoring-pod
          project: banking
      spec:
        containers:
        - name: monitoring
          image: k3d-banking-registry:5000/banking-monitoring:local
          ports:
          - containerPort: 3000
