apiVersion: k3d.io/v1alpha2
kind: Simple
name: banking
servers: 1
agents: 4
image: rancher/k3s:v1.20.7-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
registries:
  use:
    - k3d-banking-registry:5000
options:
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
