apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
    replicas: 3
    selector:
      matchLabels:
        app: customer-pod
    template:
      metadata:
        labels:
          app: customer-pod
          project: banking
      spec:
        containers:
        - name: customer
          image: k3d-banking-registry:5000/banking-customer:local
          ports:
          - containerPort: 3000
