apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
  labels:
    app: transactions
spec:
    replicas: 3
    selector:
      matchLabels:
        app: transactions-pod
    template:
      metadata:
        labels:
          app: transactions-pod
          project: banking
      spec:
        containers:
        - name: transactions
          image: k3d-banking-registry:5000/banking-transactions:local
          ports:
          - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 9
            periodSeconds: 20
